//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkstraSim.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SnackbarMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SnackbarMessages() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EkstraSim.Shared.Resources.SnackbarMessages", typeof(SnackbarMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Niezdefiniowany błąd..
        /// </summary>
        public static string Error_Base {
            get {
                return ResourceManager.GetString("Error_Base", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd deserializacji..
        /// </summary>
        public static string Error_Deserialize {
            get {
                return ResourceManager.GetString("Error_Deserialize", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd podczas pobierania danych: .
        /// </summary>
        public static string Error_Get {
            get {
                return ResourceManager.GetString("Error_Get", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak lig w bazie..
        /// </summary>
        public static string Error_Leagues_Null {
            get {
                return ResourceManager.GetString("Error_Leagues_Null", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak meczy w bazie..
        /// </summary>
        public static string Error_Matches_Null {
            get {
                return ResourceManager.GetString("Error_Matches_Null", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak sezonów w bazie..
        /// </summary>
        public static string Error_Seasons_Null {
            get {
                return ResourceManager.GetString("Error_Seasons_Null", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono symulowanego meczu..
        /// </summary>
        public static string Error_SimulatedMatch_NotFound {
            get {
                return ResourceManager.GetString("Error_SimulatedMatch_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono symulowanej rundy..
        /// </summary>
        public static string Error_SimulatedRound_NotFound {
            get {
                return ResourceManager.GetString("Error_SimulatedRound_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak symulowanych rund w bazie..
        /// </summary>
        public static string Error_SimulatedRounds_Null {
            get {
                return ResourceManager.GetString("Error_SimulatedRounds_Null", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak symulacji w bazie..
        /// </summary>
        public static string Error_Simulations_Null {
            get {
                return ResourceManager.GetString("Error_Simulations_Null", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak drużyn w bazie..
        /// </summary>
        public static string Error_Teams_Null {
            get {
                return ResourceManager.GetString("Error_Teams_Null", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało sie zaktualizować średnich ligowych..
        /// </summary>
        public static string League_Averages_Update_Failed {
            get {
                return ResourceManager.GetString("League_Averages_Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaktualizowane średnie ligowe..
        /// </summary>
        public static string League_Averages_Updated {
            get {
                return ResourceManager.GetString("League_Averages_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się zaktualizować wyniku spotkania..
        /// </summary>
        public static string Match_Result_Update_Failed {
            get {
                return ResourceManager.GetString("Match_Result_Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaktualizowano wynik spotkania..
        /// </summary>
        public static string Match_Result_Updated {
            get {
                return ResourceManager.GetString("Match_Result_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrć danych sezonów..
        /// </summary>
        public static string Seasons_Get_Failed {
            get {
                return ResourceManager.GetString("Seasons_Get_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać symulacji danego meczu..
        /// </summary>
        public static string Simulations_Match_Get_Failed {
            get {
                return ResourceManager.GetString("Simulations_Match_Get_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać symulacji danej rundy..
        /// </summary>
        public static string Simulations_Round_Get_Failed {
            get {
                return ResourceManager.GetString("Simulations_Round_Get_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać symulacji rund..
        /// </summary>
        public static string Simulations_Rounds_Get_Failed {
            get {
                return ResourceManager.GetString("Simulations_Rounds_Get_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać symulacji danego sezonu..
        /// </summary>
        public static string Simulations_Season_Get_Failed {
            get {
                return ResourceManager.GetString("Simulations_Season_Get_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się zaktualizować średnich drużyn..
        /// </summary>
        public static string Team_Averages_Update_Failed {
            get {
                return ResourceManager.GetString("Team_Averages_Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaktualizowano średnie drużyn..
        /// </summary>
        public static string Team_Averages_Updated {
            get {
                return ResourceManager.GetString("Team_Averages_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać listy drużyn..
        /// </summary>
        public static string Teams_Get_Failed {
            get {
                return ResourceManager.GetString("Teams_Get_Failed", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać porównania modeli..
        /// </summary>
        public static string Research_Comparison_Get_Failed {
            get {
                return ResourceManager.GetString("Research_Comparison_Get_Failed", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się zaimportować pliku CSV..
        /// </summary>
        public static string Research_Import_Failed {
            get {
                return ResourceManager.GetString("Research_Import_Failed", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Import zakończony..
        /// </summary>
        public static string Research_Import_Succeeded {
            get {
                return ResourceManager.GetString("Research_Import_Succeeded", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać metryk badania..
        /// </summary>
        public static string Research_Metrics_Get_Failed {
            get {
                return ResourceManager.GetString("Research_Metrics_Get_Failed", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać listy modeli..
        /// </summary>
        public static string Research_Models_Get_Failed {
            get {
                return ResourceManager.GetString("Research_Models_Get_Failed", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać predykcji..
        /// </summary>
        public static string Research_Predictions_Get_Failed {
            get {
                return ResourceManager.GetString("Research_Predictions_Get_Failed", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się wyznaczyć predykcji kolejki..
        /// </summary>
        public static string Research_Predict_Failed {
            get {
                return ResourceManager.GetString("Research_Predict_Failed", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Badanie uruchomione — obliczenia trwają w tle..
        /// </summary>
        public static string Research_Run_Created {
            get {
                return ResourceManager.GetString("Research_Run_Created", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się uruchomić badania..
        /// </summary>
        public static string Research_Run_Create_Failed {
            get {
                return ResourceManager.GetString("Research_Run_Create_Failed", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać badania..
        /// </summary>
        public static string Research_Run_Get_Failed {
            get {
                return ResourceManager.GetString("Research_Run_Get_Failed", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać listy badań..
        /// </summary>
        public static string Research_Runs_Get_Failed {
            get {
                return ResourceManager.GetString("Research_Runs_Get_Failed", resourceCulture);
            }
        }

        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać struktury sezonu..
        /// </summary>
        public static string Research_Structure_Get_Failed {
            get {
                return ResourceManager.GetString("Research_Structure_Get_Failed", resourceCulture);
            }
        }
    }
}
