//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkstraSim.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SnackbarMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SnackbarMessages() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EkstraSim.Shared.Resources.SnackbarMessages", typeof(SnackbarMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało sie zaktualizować średnich ligowych..
        /// </summary>
        public static string League_Averages_Update_Failed {
            get {
                return ResourceManager.GetString("League_Averages_Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaktualizowane średnie ligowe..
        /// </summary>
        public static string League_Averages_Updated {
            get {
                return ResourceManager.GetString("League_Averages_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się zaktualizować wyniku spotkania..
        /// </summary>
        public static string Match_Result_Update_Failed {
            get {
                return ResourceManager.GetString("Match_Result_Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaktualizowano wynik spotkania..
        /// </summary>
        public static string Match_Result_Updated {
            get {
                return ResourceManager.GetString("Match_Result_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrć danych sezonów..
        /// </summary>
        public static string Seasons_Get_Failed {
            get {
                return ResourceManager.GetString("Seasons_Get_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać symulacji danego meczu..
        /// </summary>
        public static string Simulations_Match_Get_Failed {
            get {
                return ResourceManager.GetString("Simulations_Match_Get_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać symulacji danej rundy..
        /// </summary>
        public static string Simulations_Round_Get_Failed {
            get {
                return ResourceManager.GetString("Simulations_Round_Get_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać symulacji rund..
        /// </summary>
        public static string Simulations_Rounds_Get_Failed {
            get {
                return ResourceManager.GetString("Simulations_Rounds_Get_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać symulacji danego sezonu..
        /// </summary>
        public static string Simulations_Season_Get_Failed {
            get {
                return ResourceManager.GetString("Simulations_Season_Get_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się zaktualizować średnich drużyn..
        /// </summary>
        public static string Team_Averages_Update_Failed {
            get {
                return ResourceManager.GetString("Team_Averages_Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaktualizowano średnie drużyn..
        /// </summary>
        public static string Team_Averages_Updated {
            get {
                return ResourceManager.GetString("Team_Averages_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać listy drużyn..
        /// </summary>
        public static string Teams_Get_Failed {
            get {
                return ResourceManager.GetString("Teams_Get_Failed", resourceCulture);
            }
        }
    }
}
